language: python
python:
- '3.6'

# command to install dependencies
install:
  - pip install -r requirements.txt

script: python setup.py test

deploy:
  provider: pypi
  user: "unique1o1"
  password:
    secure: aOF0cWubcljLTnT74J3ph+OLkGvkKwWF1Kb2pHs8ShOCUhMWJzzBTCbGNrXkiNH9IYFQlidSD+7/1K1g9u4wruLUHpjQ5gvCAd06BfJ3kLhUcRYF4jKJWi9btDHa4JAj4F5QviKBGnA4+ARWg71E8qptw7Pi8c1G65TXF3px2HGYrXC20LfYUpoPbF5ylEf7kuWeD0RKISmgfjHsTMjf1gaO4YmKU0hIFB1noj/hrPiweEA6oZfeDSEFZ5xVjeOPtfieYYLiY20pWb4MVgywFRpJS9X6ySxtkY+eeAGMUNCl5M8eoRo8lfJ4Ogk7kOGNJ/mY4Tk+Dsd++r4FiMNy3WXeMxewXY9iXgveYsm7slenOKTeAfGyabgEMSPGgTC5D2Q+M66t/spt1XQPtzymkzArh8o7JFmD+cMik/Tira/SSjqZCbZUkhYrgoAIDdu4Bgqv7nQ2iDrA6kRp+J0YPmpJkhF6JjS1fI2zdhsvjv1DIGUG/uNtFAh1Oz5gxi3JDRaTumKp2NUjNKz1mPEKKO15Cl4byCtXIaHQ3jESGD7t75KaYrO1fewFxz9Eik1QcA34bhj9vjZSUJRdHjjKkxT1Wx/NFyp8mr89X6ZqhE8P+q/fxW5f6/0NlyYTqJqVvh/AMJ2Q+aREZh0riRBUzIEBYtnma/ltEhBOUPms0ko=
  on:
    tags: true
branch: pypi_packages
